<?php

class config extends pf_controller
{
    public function index()
    {
        $this->checkLogin();
        
        $userlevels = CMC::getCMCSetting('pageaccess');
        //lock to user level
        pf_auth::lockPage($userlevels['config'], 'Sorry, You do not have access to this page!');
        
        $data = array('bukkit_dir'=> CMC::getCMCSetting('bukkit_dir'));
        mcController::getMCConfig($data['bukkit_dir'].DS.'server.properties');
        $data = mcController::$server_data;
        $this->loadView('config/config_page.php',$data);
    }
    
    public function savesettings()
    {
        if (!$_SERVER['REQUEST_METHOD']=='POST')
        {
            pf_core::redirectUrl(pf_config::get('main_page'));
        }
        
        CMC::log('New server.properties Generated by: '.pf_auth::getVar('user'));
                
        $output = "#Generated by CMC @ ". date('m/d/Y g:h:i:s a')."\n";
        foreach ($_POST as $key=>$setting)
        {
            $cleaned = preg_replace("/[^a-zA-Z0-9]+/", "", $setting);
            $output.= $key."=".$cleaned."\n";
        }
        $file = CMC::getCMCSetting('bukkit_dir').DS.'server.properties';
        
        if (!file_put_contents($file, $output))
        {
            pf_events::dispayFatal('Unable to save Server.properties. Does www-data have write permissions?');
        }
        
        $data=array('file'=>$output);
        $this->loadView('config/complete_page.php', $data);
    }
    
}
?>
