<?php

class config extends pf_controller
{
    public function index()
    {
        $this->checkLogin();
        
        $data = array('bukkit_dir'=>$this->getdir());
        $this->loadLibrary('server_conf');
        server_conf::grabConfig($data['bukkit_dir'].DS.'server.properties');
        $data = server_conf::$server_data;
        $this->loadView('config/config_page.php',$data);
    }
    
    
    private function getdir()
    {
        $settings = new pf_json();
        $settings->readJsonFile(pf_config::get('Json_Settings'));
        
        $bukkit_dir = $settings->get('bukkit_dir');
        return $bukkit_dir;
    }

    public function savesettings()
    {
        if (!$_SERVER['REQUEST_METHOD']=='POST')
        {
            pf_core::redirectUrl(pf_config::get('main_page'));
        }
        $this->loadLibrary('server_conf');
                
            $output = "#Generated by CMC @ ". date('m/d/Y g:h:i:s a')."\n";
        foreach ($_POST as $key=>$setting)
        {
            $cleaned = preg_replace("/[^a-zA-Z0-9]+/", "", $setting);
            $output.= $key."=".$cleaned."\n";
        }
        $file = $this->getdir().DS.'server.properties';
        
        if (!file_put_contents($file, $output))
        {
            pf_events::dispayFatal('Unable to save Server.properties. Does www-data have write permissions?');
        }
        
        $data=array('file'=>$output);
        $this->loadView('config/complete_page.php', $data);
    }
    
}
?>
